// ══════════════════════════════════════════════════════════════════
// FitMe — Error Telemetry (Friends Alpha Item 7 — Minimal Error/Crash Telemetry)
// Exclusive responsibility: bounded, allowlist-only operational error visibility for the
// Friends Alpha trial. Captures ONLY: a closed error `code`, a closed short `module`/
// `operation` identifier, a length-capped technical `message`, APP_VERSION, a client
// timestamp, and a `retryable` boolean — never chat/meal/memory/safety content, never a raw
// stack trace, never request/response bodies. report()'s own buildAllowedPayload() below
// constructs a NEW object containing ONLY these seven fields from a caller's input — any
// other key a caller's input object might carry (a stack trace, chat text, a meal object,
// anything) is never read and never persisted. This is the allowlist boundary: safety comes
// from a closed set of PAYLOAD FIELDS (this file) plus a closed, small, explicitly-reviewed
// set of INTEGRATION POINTS that ever call report() (js/app.js) — never from attempting to
// sanitize arbitrary content after the fact.
//
// Loaded FIRST in index.html (before the Firebase SDKs) so its own global handlers
// (window 'error'/'unhandledrejection') are registered before any other script on the page
// can run — including a hypothetical future regression of Item 1's own load-order defect
// class. Self-installing: requires no configure() call to start listening.
//
// GLOBAL vs. EXPLICITLY-REVIEWED integration points (Product/Architecture, Friends Alpha Item
// 7 Final Review, Correction 1): the two global handlers below (handleUncaughtError/
// handleUnhandledRejection) are universal catch-alls — they can be reached by a throw from
// ANYWHERE in the codebase, including a future one this file's own authors never reviewed. For
// that reason, and ONLY for that reason, neither ever supplies a `message` to report() — their
// persisted payload is structural metadata only (code/module/operation/appVersion/retryable/
// timestamps), content-safe by construction (the call site itself never reads the browser's
// own message/reason text into anything passed to report()), never by inspecting, sanitizing,
// denylisting, or hashing runtime text after the fact. The small, explicit, hand-reviewed set
// of application integration points in js/app.js remain free to supply a bounded `message`
// ONLY where repository evidence proves the value is generated by trusted application/SDK
// machinery (e.g. PersistenceGateway.classifyError()'s own Firestore-SDK-generated text) and
// cannot contain user content — see each of those call sites' own comment for that evidence.
//
// Pre-auth / not-yet-configured / signed-out safety: configure() is called later (js/app.js),
// once db/currentUser/SessionLifecycle all exist. Until configure() has run, and whenever no
// authenticated user currently exists, every report() call is console-only — no Firestore
// write is ever attempted without a real, currently-authenticated uid. This is deliberate: no
// anonymous identity tracking is ever invented here, and no orphaned pre-auth/post-signout
// Firestore record is ever created (Friends Alpha Item 7's own approved boundary).
//
// Fail-open by construction: every path that touches deps/Firestore is wrapped in try/catch;
// a telemetry failure (missing config, a rejected Firestore write, anything) can never throw
// back into a caller or interrupt normal application behavior. report() itself never throws.
// ══════════════════════════════════════════════════════════════════
(function () {
  'use strict';

  var MAX_MESSAGE_LEN = 300;
  var MAX_FIELD_LEN = 64;
  var MAX_APP_VERSION_LEN = 32;
  // Bounded rate guard (Friends Alpha Item 7 — "we do not need commercial-scale machinery"):
  // a simple per-session cap protects against a runaway loop of distinct errors, on top of the
  // per-error-class dedup below (which already prevents the far more common case — one
  // recurring error firing repeatedly). Chosen to comfortably cover a genuine multi-failure
  // debugging session for one of ~10-20 known Friends Alpha users without allowing an
  // unbounded write loop; not derived from any measured production volume (none exists yet).
  var MAX_WRITES_PER_SESSION = 20;

  var deps = null; // set only once configure() is called — before that, every report() is console-only
  var _seenThisSession = {};   // dedup set — bounded implicitly by MAX_WRITES_PER_SESSION (see below)
  var _writeCountThisSession = 0;

  // A fresh configure() call — and, once SessionLifecycle exists, every auth-session reset
  // (sign-in/sign-out/user switch) — starts a fresh telemetry budget. Registered here, inside
  // configure(), rather than at module-load time: this file is deliberately the very first
  // <script> in index.html (see file header), loaded before js/sessionLifecycle.js itself, so
  // window.SessionLifecycle does not exist yet at this file's own load time — only later, when
  // js/app.js calls configure(), is it guaranteed to be available.
  function configure(injected) {
    deps = injected || {};
    _seenThisSession = {};
    _writeCountThisSession = 0;
    if (typeof window !== 'undefined' && window.SessionLifecycle && typeof window.SessionLifecycle.registerCleanup === 'function') {
      // REM-002 pattern (mirrors js/memory.js's own registerCleanup('memory', ...) precedent
      // exactly): idempotent by name — a re-configure() never registers a duplicate cleanup.
      // This reset does not itself prevent a write from landing under the wrong user — no such
      // risk exists here, since report() below captures user.uid synchronously, before any
      // await, so a Firestore write is always addressed to whichever uid was actually
      // authenticated at the moment the error occurred. This reset only prevents one user's
      // dedup/rate state from silently suppressing a genuinely new error for a different,
      // later-signed-in user (Friends Alpha Item 7 requirement H).
      window.SessionLifecycle.registerCleanup('errorTelemetry', function () {
        _seenThisSession = {};
        _writeCountThisSession = 0;
      });
    }
  }

  function isNonEmptyString(s) { return typeof s === 'string' && s.length > 0; }
  function truncate(s, max) { return isNonEmptyString(s) ? s.slice(0, max) : ''; }

  // The ONLY function that ever constructs the object a caller's entry can turn into. Reads
  // exactly five fields off `entry` (code/module/operation/message/retryable) — never any
  // other key. See file header for the full allowlist rationale.
  function buildAllowedPayload(entry) {
    entry = (entry && typeof entry === 'object') ? entry : {};
    return {
      code: isNonEmptyString(entry.code) ? truncate(entry.code, MAX_FIELD_LEN) : 'UNKNOWN',
      module: isNonEmptyString(entry.module) ? truncate(entry.module, MAX_FIELD_LEN) : 'UNKNOWN',
      operation: truncate(entry.operation, MAX_FIELD_LEN),
      message: truncate(entry.message, MAX_MESSAGE_LEN),
      appVersion: (deps && isNonEmptyString(deps.appVersion)) ? truncate(deps.appVersion, MAX_APP_VERSION_LEN) : '',
      retryable: entry.retryable === true,
      clientTimestamp: Date.now()
    };
  }

  // Dedup identity is structural only (code/module/operation) — deliberately excludes
  // `message`, so two occurrences of "the same" logical error are recognized as duplicates
  // even if a technical message's exact text varies slightly between occurrences.
  function dedupKey(payload) {
    return payload.code + '|' + payload.module + '|' + payload.operation;
  }

  function consoleOnly(payload) {
    try {
      console.error('[FitMe telemetry] ' + payload.module + '/' + payload.code +
        (payload.operation ? '/' + payload.operation : '') +
        (payload.message ? ': ' + payload.message : ''));
    } catch (e) { /* never throw from telemetry */ }
  }

  // The single public entry point every integration point (the two self-installed global
  // handlers below, plus the small, explicit set of already-caught application failures wired
  // in js/app.js) calls. Never throws — every branch below is defensive.
  function report(entry) {
    var payload;
    try {
      payload = buildAllowedPayload(entry);
    } catch (e) {
      return; // defensive only — buildAllowedPayload() has no code path that should throw
    }

    // Always — pre-auth-safe, gives local/dev console visibility regardless of write outcome,
    // and is the ENTIRE behavior for any error that occurs before configure() or while signed out.
    consoleOnly(payload);

    if (!deps || !deps.errorLogRepository || typeof deps.getCurrentUser !== 'function') return;
    var user;
    try { user = deps.getCurrentUser(); } catch (e) { return; }
    if (!user || !user.uid) return; // no authenticated user — never orphaned, never anonymous

    var key = dedupKey(payload);
    if (_seenThisSession[key]) return;               // G — already reported this class this session
    if (_writeCountThisSession >= MAX_WRITES_PER_SESSION) return; // bounded rate guard

    _seenThisSession[key] = true;
    _writeCountThisSession++;

    try {
      var result = deps.errorLogRepository.create(user.uid, payload);
      if (result && typeof result.catch === 'function') {
        result.catch(function (e) {
          try { console.warn('[FitMe telemetry] write failed:', e && e.message); } catch (_e) {}
        });
      }
    } catch (e) {
      try { console.warn('[FitMe telemetry] write threw synchronously:', e && e.message); } catch (_e) {}
    }
  }

  // Named, separately-callable handler bodies (rather than inline listener closures) so they
  // can be unit-tested directly in Node — no DOM/window required to prove "a given browser
  // error-event maps to the correct report() call" — while their actual wiring to real browser
  // events (below) is verified separately, by source-text assertion, the same "wiring test"
  // convention this repository's own tests/*Wiring.test.js files already use for anything that
  // cannot be directly exercised without a real DOM. Every body is wrapped in try/catch: an
  // error-reporting handler that itself throws would be a genuine regression, never acceptable.
  //
  // CONTENT-SAFETY CORRECTION (Product/Architecture, Friends Alpha Item 7 Final Review,
  // Correction 1): these two handlers are universal catch-alls — unlike the small, explicitly
  // reviewed application integration points in js/app.js, a future `throw new Error(userText)`
  // anywhere in the codebase could route arbitrary user-authored content through here. Product
  // does not accept that residual risk. Neither handler below EVER supplies a `message` to
  // report() — the persisted payload for both is structural metadata only
  // (code/module/operation/appVersion/retryable/timestamps), content-safe BY CONSTRUCTION (the
  // call site itself never reads event.message/event.reason.message into anything passed to
  // report()), never by inspecting, sanitizing, denylisting, or hashing the runtime text after
  // the fact. Local console visibility of the raw browser-supplied text is preserved separately
  // below, entirely outside the report()/persisted-payload pipeline — see each function's own
  // explicit, clearly-labeled console-only line.
  function handleUncaughtError(event) {
    try {
      // Console-only, local-developer visibility — NEVER touches report() or the persisted
      // payload. The browser's own native console output already shows this by default (this
      // handler never calls event.preventDefault()); this explicit line only makes that intent
      // unambiguous in source, not a new capability or a new data path.
      try { console.error('[FitMe telemetry] GLOBAL/UNCAUGHT_ERROR (console-only, never persisted):', event && event.message); } catch (e) {}
      report({ code: 'UNCAUGHT_ERROR', module: 'GLOBAL', operation: '' }); // structural metadata only — no message (Correction 1)
    } catch (e) { /* never throw from a global error handler */ }
  }

  function handleUnhandledRejection(event) {
    try {
      // Console-only, local-developer visibility — NEVER touches report() or the persisted
      // payload (see handleUncaughtError's own comment above for the full rationale).
      try { console.error('[FitMe telemetry] GLOBAL/UNHANDLED_REJECTION (console-only, never persisted):', event && event.reason); } catch (e) {}
      report({ code: 'UNHANDLED_REJECTION', module: 'GLOBAL', operation: '' }); // structural metadata only — no message, no reason, no stack (Correction 1)
    } catch (e) { /* never throw from a global rejection handler */ }
  }

  // Self-installing — registered at module-load time (no configure() call required), active
  // for the entire remaining page lifetime once this file (the first <script> in index.html)
  // executes.
  if (typeof window !== 'undefined' && typeof window.addEventListener === 'function') {
    window.addEventListener('error', handleUncaughtError);
    window.addEventListener('unhandledrejection', handleUnhandledRejection);
  }

  var API = {
    configure: configure,
    report: report,
    MAX_WRITES_PER_SESSION: MAX_WRITES_PER_SESSION,
    _internal: {
      buildAllowedPayload: buildAllowedPayload,
      dedupKey: dedupKey,
      handleUncaughtError: handleUncaughtError,
      handleUnhandledRejection: handleUnhandledRejection
    }
  };

  if (typeof window !== 'undefined') { window.ErrorTelemetry = API; }
  if (typeof module !== 'undefined' && module.exports) { module.exports = API; }
})();
